application: tuiliclub
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: src/images/favicon.ico
  upload: src/images/favicon.ico

- url: /robots.txt
  static_files: src/static/robots.txt
  upload: src/static/robots.txt

- url: /images
  static_dir: src/images

- url: /test/*
  script: src/controllers/test.py

- url: /.*
  script: src/controllers/hello.py

builtins:
- datastore_admin: on
