application: tuiliclub
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /images
  static_dir: images

- url: /test/*
  script: controllers/test.py

- url: /testuser/*
  script: controllers/test.py

- url: /.*
  script: controllers/homepage.py

builtins:
- datastore_admin: on
- remote_api: on
