application: tuiliclub
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
#for uploading and download data
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/login_required
  script: app.py
  
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /static
  static_dir: static

- url: /images
  static_dir: images

- url: /memberdata
  static_dir: memberdata

- url: /.*
  script: app.py 
